# Site settings
title: Gridville
email:
description: >-
  City builder game
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Gridville"
  #  avatar : "/assets/images/bio-photo.jpg"
  bio: "Playful experiment in city-building—and a fun excuse to dive deep into mastering Zig Lang and the Raylib graphics library."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aerkalov/gridville/"
    - label: "X / Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://x.com/aerkalov/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aerkalov/gridville/"
    - label: "X / Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://x.com/aerkalov/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
